# The purpose of this -test example is for the e2e tests of this project
#
# Usage:
#  docker-compose -p grid up --force-recreate
#  docker-compose -p grid scale mock=1 hub=1 chrome=3 firefox=3
version: '2.1'
services:
  hub:
    image: elgalu/selenium
    ports:
      - ${VNC_FROM_PORT-40650}-${VNC_TO_PORT-40700}:${VNC_FROM_PORT-40650}-${VNC_TO_PORT-40700}

  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 800 --screenHeight 600
            --timeZone "America/New_York"
            --videoRecordingEnabled false
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --cbtEnabled false
            --startTunnel false

  behat:
    hostname: behat
    image: docksal/behat
    volumes:
      - .:/src
    # Run a built-in web server for access to HTML reports
    ports:
     - 8000:8000
    entrypoint: "php -S 0.0.0.0:8000"

#  browser:
#    hostname: browser
    # Pick/uncomment one
#    image: selenium/standalone-chrome
    #image: selenium/standalone-firefox
